#pragma once
#include <vector>
#include <algorithm>
#include <string>
#include <array>
#include <unordered_map>
#include <map>
#include <iostream>
#include <cstdint>
#include <memory>
#include <utility>
#include <functional>
#include <cstring>
#include <cassert>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <cstddef>
#include <mutex>
#include <stdexcept>
#include <glm/glm.hpp>